spring:
  profiles:
    active: dev
server:
  address: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
---
#dev
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27018/photo
  config:
    activate:
      on-profile: dev
parse:
  file:
    location: car.json
---
#docker
spring:
  data:
    mongodb:
      uri: mongodb://car-image-view-mongo:27017/photo
  config:
    activate:
      on-profile: docker
parse:
  file:
    location: /app/car.json