spring:
  profiles:
    active: dev
---
#dev
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27018/photo
  config:
    activate:
      on-profile: dev
---
#docker
spring:
  data:
    mongodb:
      uri: mongodb://nginx-mongo-photo-view-mongo:27017/photo
  config:
    activate:
      on-profile: docker